[IMP] edi: Current document activity status available
mcb30/odoo-edi pull request #42
Opened 2019-05-20 22:05 UTC by joe-gb

Adding an activity status to edi.document to contain the
current activity (preparing, executing) of the document.

EDI gateway transfers commit explicitly so that each
stage of transfer>prepare>execute are visible, a
rollback will only occur for a subsection of this
transcation - a failed execution will now  leave a
prepared document that can be viewed in the UI.

2019-05-29 14:00 UTC, samueljsb approved these changes
LGTM

2019-05-29 18:00 UTC, mcb30 commented on addons/edi/tests/common.py
> +        self.cr.execute("SAVEPOINT test_cursor")
How does this handle a test case that attempts to commit multiple times?

2019-05-29 18:01 UTC, mcb30 commented
There is a failure for the automated tests on the first commit.  Please rebase to invert the order so that all commits pass all automated tests.

2019-05-29 18:11 UTC, mcb30 requested changes
I'm really not keen on the decorator that wraps the entire method.  It would seem much cleaner to have the activity lifecycle managed alongside the existing savepoints, since the savepoints already represent the well-defined bounds of document preparation/execution.  This patch seems to make it substantially harder to understand the flow of the code.

2019-05-29 18:11 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                .browse(self.ids).exists().write({'activity': 'none'})
Calling self.env(cr=temp_cr) should be sufficient to construct the new environment: this would remove a substantial amount of unnecessary clutter.

Also, the .exists() call should not be necessary.  If it is necessary, that suggests a bug elsewhere that would need to be addressed.

2019-05-29 18:11 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                    # shouldn't update the activity
This special-casing suggests to me that the scope of the decorator is too broad.

2019-05-29 18:11 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                    with self.env.cr.savepoint():
Having a savepoint created by a method decorator seems likely to confuse later readers of the code.

2019-05-29 18:11 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                with env.clear_upon_failure():
This may as well be part of the outer "with" statement.

2019-05-29 18:20 UTC, mcb30 commented
I would suggest creating a context manager that manages the changes to the "state" and "activity" fields, e.g. writes to activity in a separate cursor, yields, rewrites activity on exception, sets state on success.  This can then be called as part of the same with statement that currently creates the savepoint.

2019-05-30 10:15 UTC, kdwyer commented on addons/edi/tests/common.py
> +        self.cr.execute("SAVEPOINT test_cursor")
`TestCursor` executes `SAVEPOINT  test_cursor` every time it [commits](https://github.com/unipartdigital/odoo/blob/1d93aef9ba60b46183188b0c1275b994587790e0/odoo/sql_db.py#L457) or rolls back, so multiple commits aren't a problem.  

`TestCursor` creates a savepoint "test_cursor" when an instance is initialised, so we add our savepoint to prevent the first commit releasing the initial savepoint, because that would destroy the savepoint created by `SavepointCase` at the beginning of test method execution.

2019-05-30 15:46 UTC, kdwyer commented on addons/edi/models/edi_document.py
> +                with env.clear_upon_failure():
It could.  Do you have any objection to backslashes for long-line continuation?  We can't wrap multiple `with` statements in parentheses because [bug](https://bugs.python.org/issue12782).

2019-06-06 17:28 UTC, closed without merging

2019-06-06 17:30 UTC, joe-gb commented
https://github.com/unipartdigital/odoo-edi/pull/43
new PR created with the above comments addressed, excepting that a second cursor isn't being used to update the activity as this will break transactions in the case of a document being created in the same call - committing in the same transaction does work, though