[IMP] edi: Restrict local filesystem gateway to specific path
mcb30/odoo-edi pull request #47
Opened 2019-06-11 11:35 UTC by crwr45

If a user had permission to modify the paths of the local filesystem
gateway they were able to retrieve files from the server, provided
the user running the server has access to them.

This change adds a restriction to local filesystem connections that
they can only access files within a pre-defined path. Changing that
path requires modifying the config file and restarting the service.

User-story: 4114

2019-06-11 16:13 UTC, fish-face reviewed
Two small suggestions.

2019-06-11 16:13 UTC, fish-face commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
Is it actually necessary to check for both characters or could we use `os.path.sep`?

2019-06-11 16:13 UTC, fish-face commented on addons/edi/models/edi_connection_local.py
> +            if os.path.commonpath([real_jail_directory, os.path.realpath(directory)]) != real_jail_directory:
This check seems to be the same as that in `receive_inputs` and could be extracted.

2019-06-12 11:13 UTC, crwr45 commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
I actually prefer the `in [...]` generally for ease of adding things later, without having to make changes to the `if`.

`os.path.sep` on Windows is `'\\'`, but `'/'` is also allowed for a path separator on Windows as well, which would be missed by using `os.path.sep`

2019-06-12 11:14 UTC, crwr45 commented on addons/edi/models/edi_connection_local.py
> +            if os.path.commonpath([real_jail_directory, os.path.realpath(directory)]) != real_jail_directory:
Yup, will do

2019-06-12 13:44 UTC, mcb30 requested changes
The patch series includes one commit that fails automated tests, and also includes commits that modify earlier commits in the same series.  Could this please be rebased to produce a single patch series such that all commits pass all tests, and no patch undoes something done in an earlier patch?

Thanks,

Michael

2019-06-13 08:50 UTC, crwr45 commented
> The patch series includes one commit that fails automated tests, and also includes commits that modify earlier commits in the same series. Could this please be rebased to produce a single patch series such that all commits pass all tests, and no patch undoes something done in an earlier patch?
> 
> Thanks,
> 
> Michael

Resolved.

2019-06-14 10:06 UTC, przemub requested changes
The quick final look from me.

2019-06-14 10:06 UTC, przemub commented on addons/edi/tests/test_edi_connection_local.py
> +        # TODO Check for a specific issue (AssertRaisesIssue)
This TODO is already done - forgot to remove it :)

2019-06-14 10:06 UTC, przemub commented on addons/edi/models/edi_gateway.py
> +            jail_directory = config.get_misc('edi', 'jail_path', '/')
@crwr45 Just checking - was it decided to change the hardcoded path from /edi to /?

2019-06-14 10:53 UTC, crwr45 commented on addons/edi/tests/test_edi_connection_local.py
> +        # TODO Check for a specific issue (AssertRaisesIssue)
Please go ahead and remove it then :)

2019-06-14 10:54 UTC, crwr45 commented on addons/edi/models/edi_gateway.py
> +            jail_directory = config.get_misc('edi', 'jail_path', '/')
Yes, this was done to keep the behaviour when no config is set identical to the old behaviour.

2019-06-14 11:12 UTC, przemub commented on addons/edi/tests/test_edi_connection_local.py
> +        # TODO Check for a specific issue (AssertRaisesIssue)
Removed.

2019-06-14 11:15 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> -
Why is this blank line deleted?

2019-06-14 11:16 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +            raise PermissionError(13, _("Tried to access a folder outside the jail directory %s") % jail_directory)
This lines look suspiciously long; please wrap to match the remainder of the file.

2019-06-14 11:25 UTC, przemub approved these changes

2019-06-14 11:26 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> -
Don't know why, tbh. Adding it back.

2019-06-14 11:30 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            raise PermissionError(13, _("Tried to access a folder outside the jail directory %s") % jail_directory)
Wrapped. If you'd rather do it another way, please let me know.

2019-06-14 11:38 UTC, mcb30 requested changes
Multiple comments inline: please resolve and resubmit for a fresh review.  Thanks.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +                    continue
This is security noise without a justification, and attempts to enumerate badness ("non-regular files") rather than ensure correctness.  It would be cleaner to e.g. extend the try...except to include "else: filepath.unlink()".

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> -
Why is this blank line removed?

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> +                                 operations are restricted.""")
This cannot be a field.  A field can be edited by the Administrator user and so used to bypass the restriction.  Given that the entire purpose of this change is to prevent an Odoo Administrator user from modifying arbitrary local files, there must not be any database-level configuration involved.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> +        return jail_directory
As above: the "jail_directory" field may not be used.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> -from contextlib import contextmanager
Why has this moved?

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> +
I have omitted reviewing the tests at this stage, since the underlying mechanism needs to change anyway.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> -import socket
Why has this moved?  Please do not randomly move lines and add/remove whitespace: it simply adds noise to the diff and makes reviewing slower.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +                             autospec=True) as mock_do_transfer:
Please do not introduce extraneous whitespace

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
Why has this code changed, and to what purpose?

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +    @patchJailPath
I don't think this decorator is actually needed on all of the test methods, now that the default behaviour is to allow access to anything under '/'.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
Those are not the only possible invalid characters in a filename.  More generally: do not **ever** try to check for problems by enumerating badness.  Instead, find a way to define acceptability.

2019-06-14 11:38 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +            self.assert_allowed_path(jail_directory, filepath)
It is not obvious at the point of reading this line of code that the method will raise an exception.  It would be cleaner to have a method that checks for acceptablity of a path and returns a boolean, with the exception-raising happening here instead.

2019-06-14 11:43 UTC, przemub commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
In the previous code, issues weren't closed at the teardown, what caused every further test to fail.

2019-06-14 11:47 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
This explanation does not make sense to me.  If there are issues remaining at the end of a test, then that test is supposed to fail.

2019-06-14 11:49 UTC, przemub commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
Yeah, and the test does fail, but so does every other test in the suite ran later, even if it raises no issues by itself.

2019-06-14 11:53 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
The tests use SavepointCase.  The database state will roll back to before the issue was raised.  If you are seeing issues raised in one test affect another test, then you have a bigger problem to worry about.

2019-06-14 11:56 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
TBH, "Invalid characters" is a misnomer - what we want to do is to ensure that we can't traverse the filesystem by sending a filename containing slashes. Odoo will fail when trying to create ie. file with a name containing NUL but it will happily comply if we send something like '../file.txt'.
Will think about how to solve this better.

2019-06-14 12:06 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
Use realpath() and check the result against the jail path?

2019-06-14 12:07 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
Yeah, seems like a much more explicit approach!

2019-06-17 14:15 UTC, crwr45 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
The issue is that the assert was before the super call; The assert failure stops execution, meaning the call to `super().tearDown()` isn't run. Without this fix, a single failure in the tearDown() method resulted in many other failures and error messages about missing savepoints.

2019-06-17 15:58 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
In fact, it's enough to check it in self.assert_allowed_path, giving the full file path instead of the directory path. Therefore, I've removed this code altogether.

2019-06-17 16:14 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
What I was wondering about is whether allowing the user to exploit the form and write into different directories than the gateway path (but within the confines of the jail) makes sense. It doesn't matter if the user can modify the gateway path but a use case may arise where there is a restriced-access user, who can create attachements but not modify the gateway path.

What I'd propose is to replace this check by: 1) checking if the gateway path is inside the jail, 2) checking if each attachment is directly in the gateway path.

2019-06-18 11:44 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
From memory, the tearDown() call will roll back the database to the savepoint, and therefore roll back any issues raised.  By moving the assertion after the tearDown(), I think you have effectively just deleted the assertion (and therefore created a class of hidden false positive test passes).

2019-06-18 11:47 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
I prefer the simplicity of checking that the final path (i.e. the one that is actually used to read/write content on the filesystem) lies within the jail.  This is simpler to reason about, which is usually a good thing for security-related code.

2019-06-18 13:02 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +            if any(char in attachment.datas_fname for char in ['/', '\\']):
Alright, I'll leave it like that then.

2019-06-18 13:03 UTC, przemub commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
That's why we save the number of issues into a variable, then roll-back the database by calling super().tearDown() and only in the end assert that there were no issues raised.

2019-06-18 16:41 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
OK, that makes sense; thanks for the explanation.

2019-06-24 10:00 UTC, przemub commented
Hey @mcb30,
do you think it can be merged?

2019-06-25 22:52 UTC, mcb30 requested changes
Please resubmit for final review after addressing these comments (and ping me on Skype, so that I know when it's ready).

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +    def assert_allowed_path(self, jail_directory, test_path) -> bool:
assert_allowed_path() is no longer a suitable name (following the requested changes): please use path_allowed() or similar.

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +    def assert_allowed_path(self, jail_directory, test_path) -> bool:
Please remove the "-> bool", since nothing else in this file uses type annotations.
(Alternatively, please prepare a separate patch for the whole of odoo-edi that adds type annotations)

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +        """Did the user try to escape the jail?"""
"""Is the path within the permitted jail directory?"""

(i.e. match the truth value of the docstring with the truth value that the method returns)

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +                raise PermissionError(13,
Please don't use a magic number 13.  I have no idea what that represents.  Use a named constant instead.

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_connection_local.py
> +                raise PermissionError(13,
As above

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> +    def get_jail_path(self) -> str:
Please remove the type annotation (as above)

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> +    @api.multi
This no longer refers to self in any way (apart from the pointless self.ensure_one()), and so should be an @api.model

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/models/edi_gateway.py
> +        jail_directory = config.get_misc('edi', 'jail_path', os.path.abspath(os.sep))
os.path.abspath(os.sep) is not a clean way to construct the root directory.  Please find a cleaner way, or allow get_jail_path() to return None and handle the None at the point of use.  (Returning None may be the only clean way to make this work on non-Unix platforms.)

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
I agree with the logic here, but this patch is completely unrelated to filesystem jails.  Please make this change a separate commit.

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> +    def _check_path(self, path, mock_get_misc):
mock_get_misc is unused in this function and should not be present as a parameter

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> +        self.assertEqual(jail_path, path)
What is the purpose of this wrapper function?  It appears that calling self._check_path is just a convoluted way to call self.assertEqual(self.gateway.get_jail_path(), '.......').
Please remove this wrapper.

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> +            self.gateway.do_transfer()
This method is called only once.  Please inline it at its sole call site (avoiding unnecessary indirection).

2019-06-25 22:52 UTC, mcb30 commented on addons/edi/tests/test_edi_connection_local.py
> +            mock_get_misc.side_effect = self._fake_config({})
No need for the _fake_config() wrapper: just set mock_get_misc.return_value to the value you want to find in edi.jail_path.  You're already asserting via assert_called_once_with() that the code is looking in the correct place for the configuration key.
Please remove the _fake_config() method.

2019-06-26 13:06 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +    def assert_allowed_path(self, jail_directory, test_path) -> bool:
Okay, I'll consider making a patch later.

2019-06-26 13:08 UTC, przemub commented on addons/edi/models/edi_connection_local.py
> +                raise PermissionError(13,
Replaced with errno.EACCES.

2019-06-26 13:16 UTC, przemub commented on addons/edi/models/edi_gateway.py
> +        jail_directory = config.get_misc('edi', 'jail_path', os.path.abspath(os.sep))
I was concerned with having to handle it at the point of use but since, as you say, it won't work on platforms without a single root directory I'm replacing it with None.

2019-06-26 13:22 UTC, przemub commented on addons/edi/tests/test_edi_gateway.py
> +        self.assertEqual(num_issues, 0)
Okay, moving it to separate branch and will create a new MR.

2019-06-26 13:24 UTC, przemub commented on addons/edi/tests/test_edi_connection_local.py
> +    def _check_path(self, path, mock_get_misc):
Removed the function altogether.

2019-06-27 10:57 UTC, mcb30 commented
Merged with added Signed-off-by.

2019-06-27 10:57 UTC, closed without merging