[FIX] edi: Dont recalculate values after a failure - may be invalid
mcb30/odoo-edi pull request #54
Opened 2019-11-06 10:56 UTC by joe-gb

Clearing the fields that need to be recalculated after a failure
prevents odd failures after caught failures when Odoo recalculates
fields

2019-11-07 23:58 UTC, mcb30 requested changes

2019-11-07 23:58 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                                             env.clear_upon_failure():
Looks plausible at first glance.  Some questions:

Why self.env.cr.savepoint, but env.clear_upon_failure()?  It's not immediately clear whether or not the difference is significant. My guess is that it isn't (since self.env.cr and env.cr should be the same), and that changing to env.cr.savepoint() would produce code that is easier to read.

Is there a test case that illustrates the failure, and is fixed by this change?

There are various other places within the EDI module using "with ....env.cr.savepoint()": why is the env.clear_upon_failure() required only for these two?

Is there any valid use case for using "with ....env.cr.savepoint():" without simultaneously using "with ...env.clear_upon_failure()"?  Should using savepoint() automatically imply using clear_upon_failure()?  (Is there an alternative context manager we should be using instead that already wraps both of these?)

There is nowhere in the core Odoo code that uses clear_upon_failure() - do we understand why?

2019-11-10 02:37 UTC, joe-gb commented on addons/edi/models/edi_document.py
> +                                             env.clear_upon_failure():
I believe the `env` used in execute is the one which should hold the env.todo and env.cache data that must be cleared, `self.env.cr.savepoint` was just there before so I didn't modify it - though I see no reason not to use env here (changed)

I have now added the simplest test case I could come up with, it fails before the fix and passes after, please review - I'm fairly unfamiliar with mock and you may be able to suggest a cleaner way to produce an error in execute for testing; suggestions welcome!

The only case I can really think of, is if you're confident that some code within the savepoint isn't going to do or change anything you may rely on afterwards in event of failure - so then you don't clear your entire cache unnecessarily.. though I do believe clearing the cache always would be a safer option. I don't see any other existing context managers we could use

No, I don't know why - I see it used once in test code, it calls a `cache_invalidate()` which is used in many places. It's used once in Odoo13 now - alongside a savepoint as we are here. I see some manual usage of `reset_changes()` after rollbacks elsewhere, but this executes regardless of failure..  they should probably be using `clear_upon_failure()` instead. It seems logically correct to use `clear_upon_failure()` in our case though!

2019-11-11 14:04 UTC, mcb30 commented on addons/edi/models/edi_document.py
> +                                             env.clear_upon_failure():
Thanks for the thorough investigation and explanation.  All looks good to me now; feel free to merge.

2019-11-11 14:05 UTC, mcb30 approved these changes

2019-11-11 15:29 UTC, merged